import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import {
  ArrowLeft,
  FileText,
  Printer,
  User,
  Truck,
} from "lucide-react";
import { toast } from "sonner";
import api from "../api/axiosInstance";
import LoadingSpinner from "../components/ui/LoadingSpinner";
import EmptyState from "../components/ui/EmptyState";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Download } from "lucide-react";

const formatMoney = (value) =>
  `₹${Number(value || 0).toLocaleString("en-IN", {
    maximumFractionDigits: 2,
  })}`;

const LedgerStatement = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [ledger, setLedger] = useState(null);
  const [transactions, setTransactions] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchStatement = async () => {
    try {
      setLoading(true);

      const res = await api.get(`/ledger/${id}/statement`);

      setLedger(res.data.ledger);
      setTransactions(res.data.transactions || []);
    } catch (error) {
      toast.error(
        error.response?.data?.message || "Failed to load ledger statement"
      );
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchStatement();
  }, [id]);

  if (loading) {
    return <LoadingSpinner text="Loading ledger statement..." />;
  }

  if (!ledger) {
    return (
      <EmptyState
        icon={FileText}
        title="Ledger Not Found"
        message="The selected ledger statement could not be loaded."
      />
    );
  }

  const isCustomer = ledger.type === "CUSTOMER";
  const Icon = isCustomer ? User : Truck;

  const debitTotal = transactions.reduce(
    (sum, row) => sum + Number(row.debit || 0),
    0
  );

  const creditTotal = transactions.reduce(
    (sum, row) => sum + Number(row.credit || 0),
    0
  );

  const finalBalance =
    transactions.length > 0
      ? transactions[transactions.length - 1].balance
      : ledger.openingBalance;

      const downloadPDF = () => {
  const doc = new jsPDF("p", "mm", "a4");
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("LEDGER STATEMENT", 14, 18);

  doc.setFontSize(12);
  doc.text(ledger.name.toUpperCase(), 14, 30);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Type: ${ledger.type}`, 14, 38);
  doc.text(`Mobile: ${ledger.mobile || "-"}`, 14, 45);
  doc.text(`GST: ${ledger.gstNumber || "-"}`, 14, 52);

  doc.text(`Opening Balance: ${formatMoney(ledger.openingBalance)}`, pageWidth - 14, 38, {
    align: "right",
  });

  doc.text(`Closing Balance: ${formatMoney(finalBalance)}`, pageWidth - 14, 45, {
    align: "right",
  });

  doc.line(14, 60, pageWidth - 14, 60);

  autoTable(doc, {
    startY: 68,
    head: [["Date", "Invoice", "Type", "Debit", "Credit", "Balance"]],
    body: transactions.map((row) => [
      new Date(row.date).toLocaleDateString("en-GB"),
      row.invoiceNo || "-",
      row.voucherType,
      row.debit ? formatMoney(row.debit) : "-",
      row.credit ? formatMoney(row.credit) : "-",
      formatMoney(row.balance),
    ]),
    theme: "grid",
    headStyles: {
      fillColor: [76, 29, 149],
      textColor: 255,
      fontStyle: "bold",
    },
    styles: {
      fontSize: 9,
      cellPadding: 3,
    },
    columnStyles: {
      3: { halign: "right" },
      4: { halign: "right" },
      5: { halign: "right" },
    },
  });

  const finalY = doc.lastAutoTable.finalY + 12;

  doc.setFont("helvetica", "bold");
  doc.text("Summary", 14, finalY);

  doc.setFont("helvetica", "normal");
  doc.text(`Total Debit: ${formatMoney(debitTotal)}`, 14, finalY + 8);
  doc.text(`Total Credit: ${formatMoney(creditTotal)}`, 14, finalY + 16);
  doc.text(`Closing Balance: ${formatMoney(finalBalance)}`, 14, finalY + 24);

  doc.setFontSize(9);
  doc.text("Generated by SmartERP", 14, 285);

  doc.save(`${ledger.name}-ledger-statement.pdf`);
};

  return (
    <div className="space-y-6">
      <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate("/ledger")}
            className="rounded-2xl border border-violet-500/10 bg-white/5 p-3 hover:bg-violet-500/10"
          >
            <ArrowLeft size={22} />
          </button>

          <div className="rounded-2xl bg-violet-500/15 p-3 text-violet-400">
            <Icon size={28} />
          </div>

          <div>
            <h1 className="text-3xl font-bold">Ledger Statement</h1>
            <p className="text-slate-400">
              Transaction history and running balance.
            </p>
          </div>
        </div>

        <button
          onClick={downloadPDF}
          className="flex items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-violet-500 to-cyan-500 px-5 py-3 font-semibold text-white shadow-lg shadow-violet-500/20"
        >
          <Download size={18} />
Download PDF
        </button>
      </div>

      <div className="grid gap-5 md:grid-cols-4">
        <div className="rounded-3xl border border-violet-500/10 bg-gradient-to-br from-[#14192f] to-[#0b1020] p-5 shadow-2xl shadow-black/30 md:col-span-2">
          <p className="text-sm text-slate-400">
            {isCustomer ? "Customer" : "Supplier"}
          </p>

          <h2
            title={ledger.name}
            className="mt-2 truncate text-2xl font-bold"
          >
            {ledger.name}
          </h2>

          <div className="mt-4 grid gap-2 text-sm text-slate-400">
            <p>Mobile: {ledger.mobile || "Not added"}</p>
            <p>Email: {ledger.email || "Not added"}</p>
            <p>GST: {ledger.gstNumber || "Not added"}</p>
          </div>
        </div>

        <div className="rounded-3xl border border-violet-500/10 bg-gradient-to-br from-[#14192f] to-[#0b1020] p-5 shadow-2xl shadow-black/30">
          <p className="text-sm text-slate-400">Opening Balance</p>
          <h2 className="mt-2 truncate text-2xl font-bold text-cyan-400">
            {formatMoney(ledger.openingBalance)}
          </h2>
        </div>

        <div className="rounded-3xl border border-violet-500/10 bg-gradient-to-br from-[#14192f] to-[#0b1020] p-5 shadow-2xl shadow-black/30">
          <p className="text-sm text-slate-400">Closing Balance</p>
          <h2 className="mt-2 truncate text-2xl font-bold text-violet-400">
            {formatMoney(finalBalance)}
          </h2>
        </div>
      </div>

      <div className="grid gap-5 md:grid-cols-3">
        <div className="rounded-3xl border border-violet-500/10 bg-gradient-to-br from-[#14192f] to-[#0b1020] p-5">
          <p className="text-sm text-slate-400">Total Debit</p>
          <h2 className="mt-2 text-2xl font-bold text-emerald-400">
            {formatMoney(debitTotal)}
          </h2>
        </div>

        <div className="rounded-3xl border border-violet-500/10 bg-gradient-to-br from-[#14192f] to-[#0b1020] p-5">
          <p className="text-sm text-slate-400">Total Credit</p>
          <h2 className="mt-2 text-2xl font-bold text-amber-400">
            {formatMoney(creditTotal)}
          </h2>
        </div>

        <div className="rounded-3xl border border-violet-500/10 bg-gradient-to-br from-[#14192f] to-[#0b1020] p-5">
          <p className="text-sm text-slate-400">Transactions</p>
          <h2 className="mt-2 text-2xl font-bold">
            {transactions.length}
          </h2>
        </div>
      </div>

      {transactions.length === 0 ? (
        <EmptyState
          icon={FileText}
          title="No Transactions"
          message="No vouchers are linked with this ledger yet."
        />
      ) : (
        <div className="overflow-x-auto rounded-3xl border border-violet-500/10 bg-gradient-to-br from-[#14192f] to-[#0b1020] shadow-2xl shadow-black/30">
          <div className="min-w-[900px]">
            <div className="grid grid-cols-6 border-b border-violet-500/10 bg-white/5 px-5 py-4 text-sm font-semibold text-slate-400">
              <span>Date</span>
              <span>Invoice</span>
              <span>Type</span>
              <span className="text-right">Debit</span>
              <span className="text-right">Credit</span>
              <span className="text-right">Balance</span>
            </div>

            {transactions.map((row) => (
              <div
                key={row.id}
                className="grid grid-cols-6 border-b border-violet-500/10 px-5 py-4 text-sm transition hover:bg-white/5"
              >
                <span className="text-slate-400">
                  {new Date(row.date).toLocaleDateString("en-GB")}
                </span>

                <span className="font-semibold text-cyan-400">
                  {row.invoiceNo || "-"}
                </span>

                <span>{row.voucherType}</span>

                <span className="text-right font-semibold text-emerald-400">
                  {row.debit ? formatMoney(row.debit) : "-"}
                </span>

                <span className="text-right font-semibold text-amber-400">
                  {row.credit ? formatMoney(row.credit) : "-"}
                </span>

                <span className="text-right font-bold text-violet-400">
                  {formatMoney(row.balance)}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default LedgerStatement;