import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Package, Printer } from "lucide-react";
import { toast } from "sonner";
import api from "../api/axiosInstance";
import LoadingSpinner from "../components/ui/LoadingSpinner";
import EmptyState from "../components/ui/EmptyState";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Download } from "lucide-react";

const StockLedger = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [item, setItem] = useState(null);
  const [movements, setMovements] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchStockLedger = async () => {
    try {
      setLoading(true);
      const res = await api.get(`/items/${id}/stock-ledger`);
      setItem(res.data.item);
      setMovements(res.data.movements || []);
    } catch (error) {
      toast.error(
        error.response?.data?.message || "Failed to load stock ledger",
      );
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchStockLedger();
  }, [id]);

  if (loading) return <LoadingSpinner text="Loading stock ledger..." />;

  if (!item) {
    return (
      <EmptyState
        icon={Package}
        title="Item Not Found"
        message="Stock ledger could not be loaded."
      />
    );
  }

  const downloadPDF = () => {
    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("STOCK LEDGER", 14, 18);

    doc.setFontSize(12);
    doc.text(item.name.toUpperCase(), 14, 30);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Code: ${item.code || "-"}`, 14, 38);
    doc.text(`Unit: ${item.unit || "PCS"}`, 14, 45);
    doc.text(`Minimum Stock: ${item.minimumStock}`, 14, 52);

    doc.text(
      `Current Stock: ${item.currentStock} ${item.unit}`,
      pageWidth - 14,
      38,
      {
        align: "right",
      },
    );

    doc.line(14, 60, pageWidth - 14, 60);

    autoTable(doc, {
      startY: 68,
      head: [
        ["Date", "Invoice", "Type", "Party", "In", "Out", "Balance", "Amount"],
      ],
      body: movements.map((row) => [
        new Date(row.date).toLocaleDateString("en-GB"),
        row.invoiceNo || "-",
        row.voucherType,
        row.party || "-",
        row.inQty || "-",
        row.outQty || "-",
        row.balance,
        `Rs. ${Number(row.amount || 0).toLocaleString("en-IN")}`,
      ]),
      theme: "grid",
      headStyles: {
        fillColor: [8, 145, 178],
        textColor: 255,
        fontStyle: "bold",
      },
      styles: {
        fontSize: 8.5,
        cellPadding: 2.8,
      },
      columnStyles: {
        4: { halign: "right" },
        5: { halign: "right" },
        6: { halign: "right" },
        7: { halign: "right" },
      },
    });

    doc.setFontSize(9);
    doc.text("Generated by SmartERP", 14, 285);

    doc.save(`${item.name}-stock-ledger.pdf`);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate("/items")}
            className="rounded-2xl border border-violet-500/10 bg-white/5 p-3 hover:bg-violet-500/10"
          >
            <ArrowLeft size={22} />
          </button>

          <div className="rounded-2xl bg-cyan-500/15 p-3 text-cyan-400">
            <Package size={28} />
          </div>

          <div>
            <h1 className="text-3xl font-bold">Stock Ledger</h1>
            <p className="text-slate-400">Item-wise stock movement report.</p>
          </div>
        </div>

        <button
          onClick={downloadPDF}
          className="flex items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-violet-500 to-cyan-500 px-5 py-3 font-semibold text-white"
        >
          <Download size={18} />
          Download PDF
        </button>
      </div>

      <div className="grid gap-5 md:grid-cols-4">
        <div className="rounded-3xl border border-violet-500/10 bg-white/5 p-5 md:col-span-2">
          <p className="text-sm text-slate-400">Item</p>
          <h2 className="mt-2 truncate text-2xl font-bold">{item.name}</h2>
          <p className="mt-2 text-sm text-slate-400">
            Code: {item.code || "-"} | Unit: {item.unit || "PCS"}
          </p>
        </div>

        <div className="rounded-3xl border border-violet-500/10 bg-white/5 p-5">
          <p className="text-sm text-slate-400">Current Stock</p>
          <h2 className="mt-2 text-2xl font-bold text-cyan-400">
            {item.currentStock} {item.unit}
          </h2>
        </div>

        <div className="rounded-3xl border border-violet-500/10 bg-white/5 p-5">
          <p className="text-sm text-slate-400">Minimum Stock</p>
          <h2 className="mt-2 text-2xl font-bold text-amber-400">
            {item.minimumStock} {item.unit}
          </h2>
        </div>
      </div>

      {movements.length === 0 ? (
        <EmptyState
          icon={Package}
          title="No Stock Movement"
          message="Purchase or sales vouchers for this item will appear here."
        />
      ) : (
        <div className="overflow-x-auto rounded-3xl border border-violet-500/10 bg-white/5">
          <div className="min-w-[950px]">
            <div className="grid grid-cols-8 border-b border-violet-500/10 bg-white/5 px-5 py-4 text-sm font-semibold text-slate-400">
              <span>Date</span>
              <span>Invoice</span>
              <span>Type</span>
              <span>Party</span>
              <span className="text-right">In</span>
              <span className="text-right">Out</span>
              <span className="text-right">Balance</span>
              <span className="text-right">Amount</span>
            </div>

            {movements.map((row) => (
              <div
                key={row.id}
                className="grid grid-cols-8 border-b border-violet-500/10 px-5 py-4 text-sm hover:bg-white/5"
              >
                <span className="text-slate-400">
                  {new Date(row.date).toLocaleDateString("en-GB")}
                </span>
                <span className="font-semibold text-cyan-400">
                  {row.invoiceNo || "-"}
                </span>
                <span>{row.voucherType}</span>
                <span className="truncate">{row.party}</span>
                <span className="text-right font-semibold text-violet-400">
                  {row.inQty || "-"}
                </span>
                <span className="text-right font-semibold text-red-400">
                  {row.outQty || "-"}
                </span>
                <span className="text-right font-bold">{row.balance}</span>
                <span className="text-right">
                  ₹{Number(row.amount || 0).toLocaleString("en-IN")}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default StockLedger;
